In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
N = 10
D = 2

X = np.random.rand(N,D)

W = np.random.rand(N, D)

B = np.random.rand(1, D)

print(X)
print(W)


[[0.66801318 0.20452783]
 [0.72988639 0.2705482 ]
 [0.1554138  0.98428384]
 [0.17270821 0.22309665]
 [0.53273069 0.80160335]
 [0.06885581 0.1264238 ]
 [0.19096569 0.32971441]
 [0.06503707 0.13477831]
 [0.98714863 0.68852152]
 [0.68180444 0.4939801 ]]
[[0.33335926 0.97328658]
 [0.58638912 0.28633685]
 [0.58988583 0.48865538]
 [0.64625964 0.05616138]
 [0.80924334 0.35640056]
 [0.68146255 0.11238724]
 [0.33244998 0.52874184]
 [0.89539693 0.7256419 ]
 [0.59895698 0.72491374]
 [0.13487276 0.13652162]]


In [25]:
def Foward(X, W, B):
    z = W.T.dot(X) + B
    return 1 / ( 1 - np.exp(-z))


In [26]:
Y_hat = Foward(X,W,B)
print(Y_hat)

[[1.05175194 1.25451899]
 [1.05269055 1.14459522]]


In [68]:
type(X)
type(W)
z = np.dot(W.T, X) + B

In [74]:
print(X)
print(W.T)
print(z)

[1 2 4 4 7 4]
[5 4 2 5 2 9]
[-247 -247 -247 -247 -247 -247]
